version: "3"

services:
  postgresdb:
    build:
      context: ./backend/database
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: false
