version: "3"

services:
  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile-spring-boot
    depends_on: 
      - postgresdb

  postgresdb:
    build:
      context: ./backend/database
      dockerfile: Dockerfile-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  postgresdb-test:
#    build:
#      context: ./backend/database
#      dockerfile: Dockerfile-postgres-test
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data-test:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-react
    ports:
      - "3000:80"
    depends_on: 
      - backend

volumes:
  postgres-data:
    external: false
  postgres-data-test:
    external: false
